### ISSUE TITLE
Defaults for files without an .editorconfig file

### ISSUE THREAD

**Issue by samselikoff** [sindresorhus/editorconfig-sublime#32]
Editorconfig seems to be overriding my user preferences for new files with no `.editorconfig` file. In my Sublime preferences, I have

``` js
"tab_size": 2,
"translate_tabs_to_spaces": true
```

and yet new files start out with 4 spaces set as their default.

Is there any way to set this default within Editorconfig? I don't see any preferences under Preferences -> Package Settings.

**Comment by KevinSalter** [comment]
#### +1

When this EditorConfig plugin is active, it overrides Sublime's indentation auto-detection with its own defaults in the absence of an `.editorconfig` file.  The screenshot below shows what happens when a file is selected in the sidebar and then opened in preview mode.  You can see that Sublime is correctly trying to set the indentation to 4 spaces (arrow on the left), but is overridden (arrow on the right).  Uninstalling the plugin restores Sublime's proper auto-indentation detection and settings.

![indentation-error](https://cloud.githubusercontent.com/assets/1326627/5601860/8e248650-92d5-11e4-9695-9f677d864f2f.png)

**Comment by GrayHatter** [comment]
I lost >1h today trying to figure out what plugin was fucking with all my files.

God help you if you try to save `Preferences.sublime-settings` because it'll corrupt that file too.

Why isn't' the default, do nothing?

**Comment by luwes** [comment]
Experienced this issue too multiple times. If there is no `.editorconfig` file the plugin should indeed do nothing.

**Comment by sindresorhus** [comment]
Closing as it's working per EditorConfig behavior. If you don't like the behavior, you should open an issue here: https://github.com/editorconfig/editorconfig-core-py
